- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2
  become: yes
  tasks:
    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        
    - name: Install all required dependencies
      apt: name={{ item }} state=present
      with_items:
        - python 
        - python-setuptools 
        - python-dev 
        - build-essential 
        - python-pip 
        - python-mysqldb

    - name: Install and Configure Database
      apt: name={{ item }} state=present
      with_items:
        - mysql-server 
        - mysql-client
        
    - name: Start MySQL service
      service: 
        name: mysql
        state: started
        enabled: yes
        
    - name: Create Application Database
      mysql_db: name=employee_db state=present
      
    - name: Create Database User
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:All'
        state: present

    # - name: Execute MySQL query
      # mysql_db:
        # login_unix_socket: /var/run/mysqld/mysqld.sock
        # login_user: db_user
        # login_password: Passw0rd
        # login_db: employee_db
        # query: "INSERT INTO employees VALUES ('JOHN');"
        
    - name: Install Python Flask dependency
      pip: name={{ item }} state=present
      with_items:
        - flask 
        - flask-mysql 
    
    - name: Copy Source code
      copy: src=app.py dest=/opt/app.py
      
    - name: Start web server
      shell: "cd /opt && FLASK_APP=app.py nohup flask run --host=0.0.0.0 --port=5000 > /var/log/flask.log 2>&1 &"